#!/usr/bin/env bash
# Source this before running DiffSplat on the HPC nodes. It keeps caches,
# temporary files, and experiment side effects off /nfshomes.

set -a

DIFFSPLAT_PROJECT_ROOT="${DIFFSPLAT_PROJECT_ROOT:-/fs/nexus-scratch/gnanesh/DiffSplat}"
DIFFSPLAT_CACHE_ROOT="${DIFFSPLAT_CACHE_ROOT:-${DIFFSPLAT_PROJECT_ROOT}/out/.cache}"
DIFFSPLAT_TMPDIR="${DIFFSPLAT_TMPDIR:-${DIFFSPLAT_PROJECT_ROOT}/.tmp}"

HF_HOME="${HF_HOME:-${DIFFSPLAT_CACHE_ROOT}/huggingface}"
HF_HUB_CACHE="${HF_HUB_CACHE:-${HF_HOME}/hub}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
TORCH_HOME="${TORCH_HOME:-${DIFFSPLAT_CACHE_ROOT}/torch}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-${DIFFSPLAT_CACHE_ROOT}}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${DIFFSPLAT_CACHE_ROOT}/xdg_config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-${DIFFSPLAT_CACHE_ROOT}/xdg_data}"
PIP_CACHE_DIR="${PIP_CACHE_DIR:-${DIFFSPLAT_CACHE_ROOT}/pip}"
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-${DIFFSPLAT_CACHE_ROOT}/triton}"
MPLCONFIGDIR="${MPLCONFIGDIR:-${DIFFSPLAT_CACHE_ROOT}/matplotlib}"
WANDB_DIR="${WANDB_DIR:-${DIFFSPLAT_PROJECT_ROOT}/out/wandb}"
WANDB_CACHE_DIR="${WANDB_CACHE_DIR:-${DIFFSPLAT_CACHE_ROOT}/wandb}"
WANDB_CONFIG_DIR="${WANDB_CONFIG_DIR:-${DIFFSPLAT_CACHE_ROOT}/wandb_config}"
IMAGEREWARD_CACHE_DIR="${IMAGEREWARD_CACHE_DIR:-${DIFFSPLAT_CACHE_ROOT}/ImageReward}"
U2NET_HOME="${U2NET_HOME:-${DIFFSPLAT_CACHE_ROOT}/u2net}"
TMPDIR="${TMPDIR:-${DIFFSPLAT_TMPDIR}}"

mkdir -p \
  "${HF_HOME}" "${HF_HUB_CACHE}" "${TRANSFORMERS_CACHE}" "${TORCH_HOME}" \
  "${XDG_CACHE_HOME}" "${XDG_CONFIG_HOME}" "${XDG_DATA_HOME}" \
  "${PIP_CACHE_DIR}" "${TRITON_CACHE_DIR}" "${MPLCONFIGDIR}" \
  "${WANDB_DIR}" "${WANDB_CACHE_DIR}" "${WANDB_CONFIG_DIR}" \
  "${IMAGEREWARD_CACHE_DIR}" "${U2NET_HOME}" "${TMPDIR}"

set +a
